version: "3.7"

services:
  psql:
    image: postgres:15.3-alpine3.18
    ports:
      - "5432:5432"
    volumes:
      - ./psql/data:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - psql
    env_file:
      - .env
